version: '3.8'

services:
  # Next.js application
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://localhost:8080}
        API_BASE_INTERNAL: ${API_BASE_INTERNAL:-http://localhost:8080}
        NODE_ENV: production
    container_name: nextjs-upload-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:8080}
      - API_BASE_INTERNAL=${API_BASE_INTERNAL:-http://localhost:8080}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
